site_name: Fast Healthchecks
site_description: Healthcheck for most popular ASGI frameworks
site_url: https://github.com/shepilov-vladislav/fast-healthchecks
site_author: Vladislav Shepilov
copyright: Copyright &copy; 2024 Vladislav Shepilov

repo_name: fast-healthchecks
repo_url: https://github.com/shepilov-vladislav/fast-healthchecks
edit_uri: edit/main/docs/

plugins:
  - search
  - mkdocstrings
  - include-markdown

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.svg
  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.copy
  language: en

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true


nav:
  - Home: index.md
  - API Reference: api.md
  - Changelog: changelog.md
