name: Docs

on:
  push:
    tags:
      - "*.*.*"
    paths:
      - 'docs/**'
      - 'CHANGELOG.md'
      - 'mkdocs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:

      - uses: actions/checkout@v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@v6.7.0

      - name: Set up Python 3.13
        run: uv python install 3.13

      - run: uv sync --group=docs

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv run mkdocs gh-deploy --force
