name: Upload Python Package

on:
  push:
    tags:
      - "*.*.*"

jobs:
  PyPi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fast-healthchecks
    permissions:
      id-token: write
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6.3.1

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install the project
        run: uv sync --group=dev --group=docs --all-extras

      - name: Build the project
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
